#!/bin/sh

echo "Running detekt check..."
./gradlew detektAll
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
	echo ""
	echo "***********************************************"
	echo "                 Detekt failed                 "
	echo " Please fix the above issues before committing "
	echo "***********************************************"
	echo ""
	exit $EXIT_CODE
fi

unset EXIT_CODE